stage1exe: lexer.c tree.c hash.c stack.c parser.c ast.c symbolTable.c driver.c semantics.c codegen.c
	gcc -o stage1exe lexer.c tree.c hash.c stack.c parser.c ast.c symbolTable.c semantics.c codegen.c driver.c
