# LAVANYA SONI - 2017A7PS0151P
# KUSHAGRA AGRAWAL - 2017A7PS0107P
# SIDDHANT KHANDELWAL - 2017A7PS0127P
# GROUP - 11

compiler: lexer.c tree.c hash.c stack.c parser.c ast.c symbolTable.c driver.c codegen.c semantics.c 
	gcc -o compiler lexer.c tree.c hash.c stack.c parser.c ast.c symbolTable.c semantics.c codegen.c driver.c
